name: Postman Collection Workflow 
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: '30 02 * * *' # 8 am IST
    - cron: '00 14 * * *' # 7:30 pm IST

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20' # or '18'

      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
          -e Qa.postman_environment1.json \
          -r cli,htmlextra
          
      - name: Newman Report
        uses: actions/upload-artifact@v4.6.2
        with:
         name: Newman Report
         path: newman/*.html
        

      
             
        
      
        
      
